// Precompiled header must go first
#include "pch.h"

#include "application.h"

// Project config (generated by CMake from config/config.in)
// Available when the include path contains /Users/user/CLionProjects/qHexWalker/cmake-build-release/config
#include "config.h"

Application::Application(int &argc, char **argv) : QGuiApplication(argc, argv) {
    loggerName_ = LOGGER_NAME;
    appName_ = APP_NAME;
    appVersion_ = VERSION;
}

bool Application::eventFilter(QObject *obj, QEvent *event) { return QGuiApplication::eventFilter(obj, event); }
